package workerexec

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func (b HarnessBuilder) writeSystemPromptFile(sessionID, prompt string) (string, error) {
	if strings.TrimSpace(b.DataDir) == "" {
		return "", fmt.Errorf("cloud system prompt requires worker data directory")
	}
	path := filepath.Join(b.DataDir, "prompts", sessionKey(sessionID), "system.md")
	if err := writePrivateFile(path, []byte(strings.TrimRight(prompt, "\n")+"\n")); err != nil {
		return "", fmt.Errorf("write cloud system prompt: %w", err)
	}
	return path, nil
}

func (b HarnessBuilder) writeCursorPromptPlugin(sessionID, prompt string) (string, error) {
	if strings.TrimSpace(b.DataDir) == "" {
		return "", fmt.Errorf("Cursor system prompt requires worker data directory")
	}
	pluginDir := filepath.Join(b.DataDir, "cursor-plugins", sessionKey(sessionID))
	manifest := []byte(`{"name":"ao-cloud-standing-instructions","displayName":"AO Cloud Standing Instructions","version":"1.0.0","description":"Session-scoped standing instructions generated by AO Cloud","author":{"name":"Agent Orchestrator"}}`)
	if err := writePrivateFile(filepath.Join(pluginDir, ".cursor-plugin", "plugin.json"), manifest); err != nil {
		return "", fmt.Errorf("write Cursor system prompt plugin manifest: %w", err)
	}
	rule := "---\ndescription: AO Cloud standing instructions\nalwaysApply: true\n---\n\n" + strings.TrimRight(prompt, "\n") + "\n"
	if err := writePrivateFile(filepath.Join(pluginDir, "rules", "ao-standing.mdc"), []byte(rule)); err != nil {
		return "", fmt.Errorf("write Cursor system prompt rule: %w", err)
	}
	return pluginDir, nil
}

func sessionKey(sessionID string) string {
	return fmt.Sprintf("%x", sha256.Sum256([]byte(strings.TrimSpace(sessionID))))
}

func writePrivateFile(path string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".ao-prompt-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if err := temporary.Chmod(0o600); err != nil {
		_ = temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
